import type { Metadata } from "next";
import { Fira_Code, Inter } from "next/font/google";

import "./globals.css";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

// const inter = Inter({ subsets: ["latin"] });
const firacode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pro-folio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-baseColor">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Add other meta tags or link tags here */}
      </head>
      <body className={`${firacode.className}`}>
        <div className="hidden md:block bg-primaryLightNavyBlue m-69px rounded-lg border border-line">
          <Header />
          <div className="flex-col site-content">{children}</div>
          <Footer />
        </div>
        <div className="block md:hidden">
          <Header />
          <div className="test-box">{children}</div>
        </div>
      </body>
    </html>
  );
}
